BB-333

diff --git a/.github/workflows/ci-runner4.yml b/.github/workflows/ci-runner4.yml
--- a/.github/workflows/ci-runner4.yml
+++ b/.github/workflows/ci-runner4.yml
@@ -1,157 +1,157 @@
-name: Playwright C# Tests (Ubuntu)
+#~ name: Playwright C# Tests (Ubuntu)
 
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+#~ on:
+  #~ push:
+    #~ branches: [ main ]
+  #~ pull_request:
+    #~ branches: [ main ]
 
-permissions:
-  contents: write
+#~ permissions:
+  #~ contents: write
 
-jobs:
-  test:
-    runs-on: ubuntu-latest
+#~ jobs:
+  #~ test:
+    #~ runs-on: ubuntu-latest
 
-    steps:
-      # ----------------------------
-      # Checkout
-      # ----------------------------
-      - name: Checkout repository
-        uses: actions/checkout@v4
+    #~ steps:
+      #~ # ----------------------------
+      #~ # Checkout
+      #~ # ----------------------------
+      #~ - name: Checkout repository
+        #~ uses: actions/checkout@v4
 
-      # ----------------------------
-      # Setup .NET
-      # ----------------------------
-      - name: Setup .NET SDK
-        uses: actions/setup-dotnet@v4
-        with:
-          dotnet-version: 9.0.x
+      #~ # ----------------------------
+      #~ # Setup .NET
+      #~ # ----------------------------
+      #~ - name: Setup .NET SDK
+        #~ uses: actions/setup-dotnet@v4
+        #~ with:
+          #~ dotnet-version: 9.0.x
 
-      # ----------------------------
-      # Cache NuGet
-      # ----------------------------
-      - name: Cache NuGet packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.nuget/packages
-          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
-          restore-keys: |
-            nuget-${{ runner.os }}-
+      #~ # ----------------------------
+      #~ # Cache NuGet
+      #~ # ----------------------------
+      #~ - name: Cache NuGet packages
+        #~ uses: actions/cache@v4
+        #~ with:
+          #~ path: ~/.nuget/packages
+          #~ key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
+          #~ restore-keys: |
+            #~ nuget-${{ runner.os }}-
 
-      # ----------------------------
-      # Cache Playwright Browsers
-      # ----------------------------
-      - name: Cache Playwright browsers
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/ms-playwright
-          key: playwright-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
-          restore-keys: |
-            playwright-${{ runner.os }}-
+      #~ # ----------------------------
+      #~ # Cache Playwright Browsers
+      #~ # ----------------------------
+      #~ - name: Cache Playwright browsers
+        #~ uses: actions/cache@v4
+        #~ with:
+          #~ path: ~/.cache/ms-playwright
+          #~ key: playwright-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
+          #~ restore-keys: |
+            #~ playwright-${{ runner.os }}-
 
-      # ----------------------------
-      # Restore & Build
-      # ----------------------------
-      - name: Restore dependencies
-        run: dotnet restore
+      #~ # ----------------------------
+      #~ # Restore & Build
+      #~ # ----------------------------
+      #~ - name: Restore dependencies
+        #~ run: dotnet restore
 
-      - name: Build solution
-        run: dotnet build --no-restore
+      #~ - name: Build solution
+        #~ run: dotnet build --no-restore
 
-      # ----------------------------
-      # Install Playwright Browsers
-      # ----------------------------
-      - name: Install Playwright browsers
-        run: |
-          dotnet tool install --global Microsoft.Playwright.CLI
-          playwright install chromium --with-deps
+      #~ # ----------------------------
+      #~ # Install Playwright Browsers
+      #~ # ----------------------------
+      #~ - name: Install Playwright browsers
+        #~ run: |
+          #~ dotnet tool install --global Microsoft.Playwright.CLI
+          #~ playwright install chromium --with-deps
 
-      # ----------------------------
-      # Prepare Allure directory
-      # ----------------------------
-      - name: Prepare Allure results directory
-        run: mkdir -p allure-results
+      #~ # ----------------------------
+      #~ # Prepare Allure directory
+      #~ # ----------------------------
+      #~ - name: Prepare Allure results directory
+        #~ run: mkdir -p allure-results
 
-      # ----------------------------
-      # Run Tests (pipeline continues on failure)
-      # ----------------------------
-      - name: Run Playwright tests
-        run: dotnet test --settings allure.runsettings --no-build --no-restore
-        continue-on-error: true
+      #~ # ----------------------------
+      #~ # Run Tests (pipeline continues on failure)
+      #~ # ----------------------------
+      #~ - name: Run Playwright tests
+        #~ run: dotnet test --settings allure.runsettings --no-build --no-restore
+        #~ continue-on-error: true
 
-      # ----------------------------
-      # Debug Allure output (optional but recommended)
-      # ----------------------------
-      - name: Debug Allure files
-        if: always()
-        run: |
-          echo "Listing allure-results:"
-          ls -R allure-results || echo "No allure-results found"
+      #~ # ----------------------------
+      #~ # Debug Allure output (optional but recommended)
+      #~ # ----------------------------
+      #~ - name: Debug Allure files
+        #~ if: always()
+        #~ run: |
+          #~ echo "Listing allure-results:"
+          #~ ls -R allure-results || echo "No allure-results found"
 
       
-      - name: Ensure Allure artifact is never empty
-        if: always()
-        run: |
-            mkdir -p allure-results
-            if [ -z "$(ls -A allure-results)" ]; then
-            echo "No Allure results generated" > allure-results/EMPTY_RUN.txt
-            fi
+      #~ - name: Ensure Allure artifact is never empty
+        #~ if: always()
+        #~ run: |
+            #~ mkdir -p allure-results
+            #~ if [ -z "$(ls -A allure-results)" ]; then
+            #~ echo "No Allure results generated" > allure-results/EMPTY_RUN.txt
+            #~ fi
       
       
-      # ----------------------------
-      # Upload Allure Results
-      # ----------------------------
-      - name: Upload Allure Results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: allure-results
-          path: allure-results
-          #if-no-files-found: warn
+      #~ # ----------------------------
+      #~ # Upload Allure Results
+      #~ # ----------------------------
+      #~ - name: Upload Allure Results
+        #~ if: always()
+        #~ uses: actions/upload-artifact@v4
+        #~ with:
+          #~ name: allure-results
+          #~ path: allure-results
+          #~ #if-no-files-found: warn
 
-  report:
-    needs: test
-    if: always()
-    runs-on: ubuntu-latest
+  #~ report:
+    #~ needs: test
+    #~ if: always()
+    #~ runs-on: ubuntu-latest
 
-    steps:
+    #~ steps:
     
-      # ----------------------------
-      # Download results
-      # ----------------------------
-      - name: Download Allure Results
-        uses: actions/download-artifact@v4
-        with:
-          name: allure-results
-          path: allure-results
+      #~ # ----------------------------
+      #~ # Download results
+      #~ # ----------------------------
+      #~ - name: Download Allure Results
+        #~ uses: actions/download-artifact@v4
+        #~ with:
+          #~ name: allure-results
+          #~ path: allure-results
 
-      # ----------------------------
-      # Checkout gh-pages
-      # ----------------------------
-      - name: Checkout gh-pages branch
-        uses: actions/checkout@v4
-        with:
-          ref: gh-pages
-          path: gh-pages
+      #~ # ----------------------------
+      #~ # Checkout gh-pages
+      #~ # ----------------------------
+      #~ - name: Checkout gh-pages branch
+        #~ uses: actions/checkout@v4
+        #~ with:
+          #~ ref: gh-pages
+          #~ path: gh-pages
 
-      # ----------------------------
-      # Generate Allure Report
-      # ----------------------------
-      - name: Generate Allure Report
-        uses: simple-elf/allure-report-action@master
-        with:
-          allure_results: allure-results
-          gh_pages: allure-report
-          allure_history: allure-history
-          keep_reports: 20
+      #~ # ----------------------------
+      #~ # Generate Allure Report
+      #~ # ----------------------------
+      #~ - name: Generate Allure Report
+        #~ uses: simple-elf/allure-report-action@master
+        #~ with:
+          #~ allure_results: allure-results
+          #~ gh_pages: allure-report
+          #~ allure_history: allure-history
+          #~ keep_reports: 20
 
-      # ----------------------------
-      # Deploy to GitHub Pages
-      # ----------------------------
-      - name: Deploy Allure Report
-        uses: peaceiris/actions-gh-pages@v4
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_branch: gh-pages
-          publish_dir: allure-report
+      #~ # ----------------------------
+      #~ # Deploy to GitHub Pages
+      #~ # ----------------------------
+      #~ - name: Deploy Allure Report
+        #~ uses: peaceiris/actions-gh-pages@v4
+        #~ with:
+          #~ github_token: ${{ secrets.GITHUB_TOKEN }}
+          #~ publish_branch: gh-pages
+          #~ publish_dir: allure-report
